apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quix-environment-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quix-environment-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quix-environment-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quix-environment-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quix-environment-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE_SUFFIX
              value: {{ .Values.env.namespaceSuffix | quote }}
            - name: ENVIRONMENT_REGEX
              value: {{ .Values.env.environmentRegex | quote }}
            - name: SERVICE_ACCOUNT_NAME
              value: {{ .Values.env.serviceAccountName | quote }}
            - name: SERVICE_ACCOUNT_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: CLUSTER_ROLE_NAME
              value: {{ .Values.env.clusterRoleName | quote }}
            - name: CACHE_SYNC_PERIOD
              value: {{ .Values.env.cacheSyncPeriod | quote }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 