apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.serviceAccountName }}
  namespace: {{ .Values.env.serviceAccountNamespace }}
  labels:
    {{- include "quix-environment-operator.labels" . | nindent 4 }} 