apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.env.clusterRoleName }}-env
  labels:
    {{- include "quix-environment-operator.labels" . | nindent 4 }}
rules:
# Allows the controller to manage the custom environment resources
- apiGroups: ["quix.io"]
  resources: ["environments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]