apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.env.clusterRoleName }}-env
  labels:
    {{- include "quix-environment-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name:  {{ .Values.env.clusterRoleName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.env.clusterRoleName }}-env