apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quix-environment-operator
  labels:
    app.kubernetes.io/name: quix-environment-operator
    app.kubernetes.io/part-of: quix-environment-operator
rules:
# Allows the controller to manage the custom environment resources
- apiGroups: ["quix.io"]
  resources: ["environments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Enables the controller to update status subresource of environment resources
- apiGroups: ["quix.io"]
  resources: ["environments/status"]
  verbs: ["get", "update", "patch"]
# Required for implementing finalizers on environment resources
- apiGroups: ["quix.io"]
  resources: ["environments/finalizers"]
  verbs: ["update"]
# Allows the controller to create and manage namespaces for environments
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create", "delete"]
# Enables the controller to manage role bindings for environment access control
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "create", "delete"]
# Allows the controller to emit events for observability and troubleshooting
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"] 