apiVersion: quix.io/v1
kind: Environment
metadata:
  name: sample-environment
spec:
  # Required: Unique identifier for the environment
  # Must be 3-44 characters long, lowercase alphanumeric with hyphens (not at start/end)
  # Pattern: ^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$
  id: sample-env
  
  # Optional: Custom annotations to add to the namespace
  # All annotation keys must have the 'quix.io/' prefix
  # Protected annotations that cannot be overridden:
  # - quix.io/created-by
  # - quix.io/environment-crd-namespace
  # - quix.io/environment-resource-name
  annotations:
    quix.io/description: "Sample environment for demonstration"
    quix.io/team: "platform-team"
    quix.io/owner: "jane.doe@example.com"
    quix.io/cost-center: "42"
    
  # Optional: Custom labels to add to the namespace
  # All label keys must have the 'quix.io/' prefix
  # Protected labels that cannot be overridden:
  # - quix.io/managed-by
  # - quix.io/environment-id
  # - quix.io/environment-name
  labels:
    quix.io/tier: "development"
    quix.io/project: "data-pipeline"
    quix.io/department: "engineering"
    quix.io/expiration-date: "2023-12-31" 